### PR TITLE
adding license information

### PR DESCRIPTION
**Pull request by bbarker**
Sorry if this is a bit presumptive, I don't intent to be so - I can change it as suggested. I believe I saw the project itself is GPLv3. I think if we can put examples under the least restrictive license possible, this would be helpful for different things (including adding examples to [other sites](github.com/github/linguist/pull/3960)).

### CODE REVIEW

**Comment by bbarker** [comment]
I now see that bitbucket is supposed to be where development happens; if this looks good I can make a PR there, or you can add in directly as you see fit of course.

Thanks,

**Comment by litan** [comment]
I'm currently traveling. Let me get to this in mid-January after I get back into town.

Also, I have been thinking of moving development over to github, so hold off for now on redoing anything on bitbucket.

**Comment by litan** [comment]
Just trying to think this through. How about if we make the examples MIT Licensed?
Also, please make the LICENSE file point to installer/licenses/Kojo-license.txt (or I can, after pulling).

**Comment by bbarker** [comment]
Sounds good. Incidentally, what is the need for the two license files: Kojo-license.txt and Kojoi-license.txt?

Feel free to close this pull and restructure it as you suggest. I guess we need a Kojo-examples-license.txt file that denotes that files ending in .kojo are including in the following (MIT) license, contained in the same file.

**Comment by litan** [comment]
> what is the need for the two license files: Kojo-license.txt and Kojoi-license.txt?
The second one is pulled up in the installer (and doesn't have line breaks). The first one has line breaks for easier reading. Not DRY, I know.

I'll make the agreed upon changes...

**Pull request closed without merging**
