### PR TITLE
Spanish Translate - Level 1

### PR DESCRIPTION
**Pull request by GuillermoOvejeroSanchez**

### CODE REVIEW

**Comment by litan** [comment]
Thanks for the contribution, Guillermo.

**Comment by litan** [comment]
Can you check the level 2 translation, too, please (as per this - https://github.com/litan/kojo/pull/25). Or request the author of the level-2 pull request to check it (I'm assuming you know him).

**Comment by GuillermoOvejeroSanchez** [comment]
Yes i know him, we would check it as soon as we can!

**Comment by litan** [comment]
Ok, thanks. Let me know when you are done, so that I know it's ready for the next release...

**Comment by litan** [comment]
Please follow up on - https://github.com/litan/kojo/pull/26. There's a compilation error in the translated instruction palette.

**Pull request merged**
