### PR TITLE
Create level2_es.properties

### PR DESCRIPTION
**Pull request by AlbertoRRM**
Level2 spanish support

### CODE REVIEW

**Comment by litan** [comment]
Thanks. Will merge and carry out the steps to integrate into Kojo soon.

**Comment by litan** [comment]
This has been integrated into Kojo. Please check and let me know if everything looks fine.

**Comment by GuillermoOvejeroSanchez** [comment]
Hey the spanish lang is working but it seems a bit difficult to know what the spanish commands are (witohut looking the translation)
since the instruction palette stays in English and doesnt translate to Spanish
image

**Comment by litan** [comment]
To translate the instruction palette (which currently belongs to a level-3 translation), you will need to translate the following file:
https://github.com/litan/kojo/blob/master/src/main/resources/samples/instruction-palette.kojo

A similar translation was recently done for Turkish:
https://github.com/litan/kojo/blob/master/src/main/resources/samples/tr/instruction-palette.kojo

In the absence of such a translation, students will have to be made aware of the spanish commands via documentation.

**Comment by GuillermoOvejeroSanchez** [comment]
Oh sorry then I didn't know that!
I think the rest looks fine, I don't know if I missed something.
We maybe do another PR for level-3, from now to then if we see some typos will add the corrections. :D

**Comment by litan** [comment]
Sounds good!
For corrections to the level-2 translation, you can directly modify the following file:
https://github.com/litan/kojo/blob/master/src/main/scala/net/kogics/kojo/lite/i18n/esInit.scala

**Pull request merged**
